### PR TITLE
Development

### PR DESCRIPTION
**Pull request by adewaleK**
I have just improved the semantic nature of my Html file according to the last TSE's review. I will appreciate your timely review of the changes so I can move on.

Thanks.

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
Pull Request under review by David Elí 👨‍💻

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi @adewaleK . 😄 
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****

- [ ] HTML Validator error.

Screen Shot 2020-03-05 at 11 14 22 PM

This error raise because you are using a "header" tag to encapsulate all the content inside the body.
You can fix this by simply changing the "header" to a "div" tag. ;) 
But also I'm going to drop here an image where you can see the correct use of commons tags like header, body, etc. ⬇️ 

This can change according to the project you're building.

Screen Shot 2020-03-05 at 11 20 06 PM

All the elements header, navbar, sidebar, aside, footer commonly goes inside the body tag.

****
### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

### Important note. ☢️ 
When you already have done the change required there's no need to open a new pull request, please submit this pull request. 🙏 
****

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by lekegitrepo** [comment]
### Excellent work brother 💯  🥇 
**_The page looks great now. The project is approved_**

### Optional:
- Check the image link of the apple logo and also put it in the right position.

image


### Reviewed by: [TSE] Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved

**Pull request merged**
